### ISSUE TITLE
week 8 : deploy the image to openshift

### ISSUE THREAD

**Issue by merlinpr4** [tcd-ibm/sweng.kanban.backend#20]

**Comment by cppavel** [comment]
Tried to set up cluster, IBM, AWS and GCP cost money, so will definitely have to go with developer sandbox. Need to decide: create cluster and use Github Actions, create automation in the sandbox which will be triggered on images updates in quay.io. Benefits for github actions: there seems to be a guide for that and we can easily extend the pipeline, problems: not clear how to set up the cluster in sandbox. Automation in developer sandbox, benefits: probably easier to set up, drawbacks: not clear what template to use and not concrete guide available

**Comment by cppavel** [comment]
finalized, 2 Github Actions workflows, one for pushing and the other for deployment. Turns out access to cluster in the sandbox was very easy, using the CLI provided. Had to set up a "robot" account in openshift sandbox to ensure that token does not have to be regenerated every day. Significant problems experience when trying to deploy the image: service was not created and it was hard to understand the reason. Turns out the image tags have to explicitly contain the fact that certain port was exposed for the service and router to be created. Currently fixed with hard coding the port expose part in Dockerfile need to find a workaround on how to use environment variables with buildah (switched build image from docker to buildah also) and Dockerfiles.
